### PR TITLE
Feature/jjdd8fpo 7

### PR DESCRIPTION
**Pull request by lukaszwolek**

### CODE REVIEW

**Comment by isacademyci** [comment]
Build triggered for original commit.

**Comment by isacademyci** [comment]
Build started for original commit.

**Comment by isacademyci** [comment]
Build finished.

**Comment by isacademyci** [comment]
Build triggered for original commit.

**Comment by isacademyci** [comment]
Build started for original commit.

**Comment by isacademyci** [comment]
Build finished.

**Comment by lukaszwolek** [comment]
konflikty plikow

**Pull request closed without merging**
